# Defining the compose version
services:
  crates:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
    env_file: ./.env
    ports:
      - "8000:8000"
    restart: "always"
    user: 1000:1000