[project]
name = "crates"
version = "0.14.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic==1.18.1",
    "anyio==4.12.1",
    "fastapi==0.128.0",
    "google-cloud-vision==3.15.0",
    "matplotlib==3.10.8",
    "numpy==2.5.2",
    "pillow==12.1.1",
    "pulp>=3.3.2",
    "pydantic==2.12.5",
    "python-dotenv==1.2.1",
    "schwifty==2026.1.0",
    "sentry-sdk==2.50.0",
    "sepaxml==2.7.0",
    "sqlalchemy==2.0.46",
    "sqlmodel==0.0.31",
    "uvicorn==0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]
test = [
    "pytest>=9.1.1",
    "gurobipy>=13.0.2",
]
