[project]
name = "crates"
version = "0.14.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic==1.19.1",
    "anyio==4.14.2",
    "fastapi==0.141.1",
    "google-cloud-vision==3.15.0",
    "matplotlib==3.11.1",
    "numpy==2.5.2",
    "pillow==12.1.1",
    "pulp>=3.3.2",
    "pydantic==2.13.4",
    "python-dotenv==1.2.1",
    "schwifty==2026.1.0",
    "sentry-sdk==2.68.0",
    "sepaxml==2.7.0",
    "sqlalchemy==2.0.52",
    "sqlmodel==0.0.39",
    "uvicorn==0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]
test = [
    "pytest>=9.1.1",
    "gurobipy>=13.0.2",
]
