"""invoicenumber

Revision ID: 29ccddbfd914
Revises: 77ac6cf243d1
Create Date: 2026-01-22 23:43:20.536932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29ccddbfd914'
down_revision: Union[str, Sequence[str], None] = '77ac6cf243d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_number', sa.Integer(), nullable=False))
    op.add_column('invoice', sa.Column('billing_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_column('invoice', 'billing_date')
    op.drop_column('invoice', 'invoice_number')
    # ### end Alembic commands ###
