"""Sepa

Revision ID: 360d0d5db776
Revises: 
Create Date: 2026-01-24 23:13:01.833832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '360d0d5db776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountingexport',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('export_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sepa_mandate', sa.Boolean(), nullable=False),
    sa.Column('sepa_mandate_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sepa_mandate_date', sa.Date(), nullable=True),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('fk_invoice_customer', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_invoice_customer'], ['customer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_fk_invoice_customer'), ['fk_invoice_customer'], unique=False)

    op.create_table('sepastatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_sepastatement_accountingexport', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['fk_sepastatement_accountingexport'], ['accountingexport.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sepastatement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sepastatement_fk_sepastatement_accountingexport'), ['fk_sepastatement_accountingexport'], unique=False)

    op.create_table('invoiceitem',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoiceitem_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoiceitem_invoice_id'))

    op.drop_table('invoiceitem')
    with op.batch_alter_table('sepastatement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sepastatement_fk_sepastatement_accountingexport'))

    op.drop_table('sepastatement')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_fk_invoice_customer'))

    op.drop_table('invoice')
    op.drop_table('customer')
    op.drop_table('accountingexport')
    # ### end Alembic commands ###
