"""Invoice

Revision ID: 6bfebc4bb17e
Revises: a5bc01cf53e3
Create Date: 2026-01-23 10:38:49.694128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bfebc4bb17e'
down_revision: Union[str, Sequence[str], None] = 'a5bc01cf53e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('billing_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('billing_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
