"""add order and crate tables

Revision ID: 919740af7008
Revises: 92ec7c71c0b0
Create Date: 2026-03-25 23:32:59.362404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '919740af7008'
down_revision: Union[str, Sequence[str], None] = '92ec7c71c0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_crate_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crate', ['assigned_crate_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_crate_id')

    # ### end Alembic commands ###
