"""added order last_seen

Revision ID: 92b6ebba9800
Revises: 38ffe087c6a6
Create Date: 2026-08-17 17:48:40.194218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92b6ebba9800'
down_revision: Union[str, Sequence[str], None] = '38ffe087c6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_changed', sa.DateTime(), nullable=False,server_default=sa.func.current_timestamp()))

    with op.batch_alter_table('orderhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_changed', sa.DateTime(), nullable=False,server_default=sa.func.current_timestamp()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderhistory', schema=None) as batch_op:
        batch_op.drop_column('last_changed')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('last_changed')

    # ### end Alembic commands ###
