"""predicted return date optional

Revision ID: 92ec7c71c0b0
Revises: 13cea898e679
Create Date: 2026-03-19 17:18:37.596447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92ec7c71c0b0'
down_revision: Union[str, Sequence[str], None] = '13cea898e679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('predicted_return_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('predicted_return_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
