"""Sepa

Revision ID: a2ac0fec48da
Revises: cf0efea311b3
Create Date: 2026-01-24 23:28:26.815009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2ac0fec48da'
down_revision: Union[str, Sequence[str], None] = 'cf0efea311b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountingexport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('export_date')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('accountingexport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
