"""Sepa

Revision ID: a61b20daded0
Revises: a2ac0fec48da
Create Date: 2026-01-25 01:03:35.693072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a61b20daded0'
down_revision: Union[str, Sequence[str], None] = 'a2ac0fec48da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sepastatement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sepastatement_fk_sepastatement_accountingexport'))

    op.drop_table('sepastatement')
    with op.batch_alter_table('accountingexport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sepa_xml', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountingexport', schema=None) as batch_op:
        batch_op.drop_column('sepa_xml')

    op.create_table('sepastatement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fk_sepastatement_accountingexport', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['fk_sepastatement_accountingexport'], ['accountingexport.id'], name=op.f('fk_sepastatement_fk_sepastatement_accountingexport_accountingexport'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sepastatement'))
    )
    with op.batch_alter_table('sepastatement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sepastatement_fk_sepastatement_accountingexport'), ['fk_sepastatement_accountingexport'], unique=False)

    # ### end Alembic commands ###
