"""Invoice

Revision ID: c5c6421a8806
Revises: 53ccf1ab7e9b
Create Date: 2026-01-23 12:56:47.418534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5c6421a8806'
down_revision: Union[str, Sequence[str], None] = '53ccf1ab7e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_status'))

    op.drop_table('invoice')
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoiceitem_invoice_id'))

    op.drop_table('invoiceitem')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_customer_number'))
        batch_op.drop_index(batch_op.f('ix_customer_first_name'))
        batch_op.drop_index(batch_op.f('ix_customer_last_name'))

    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('customer_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_number'), ['customer_number'], unique=1)

    op.create_table('invoiceitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoiceitem_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.INTEGER(), nullable=False),
    sa.Column('billing_date', sa.DATE(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=1)
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###
