"""Sepa

Revision ID: ff2e71c68e71
Revises: 360d0d5db776
Create Date: 2026-01-24 23:13:45.997297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff2e71c68e71'
down_revision: Union[str, Sequence[str], None] = '360d0d5db776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoiceitem_invoice_id'))
        batch_op.drop_constraint(batch_op.f('fk_invoiceitem_invoice_id_invoice'), type_='foreignkey')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_invoiceitem_invoice_id_invoice'), 'invoice', ['invoice_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_invoiceitem_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###
