name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Analysing the code with pylint
      run: |
        uv run --with pylint pylint $(git ls-files '*.py') --fail-under=4.0